### ISSUE TITLE
Missing lib/Loading.css 

### ISSUE THREAD

**Issue by p0rridg3** [omer73364/lazy-load-list#2]
### Description
After `npm install`, the following error appears:

```
ERROR  Failed to compile with 1 error  

This relative module was not found:
* ../lib/loading.css in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./node_modules/lazy-load-list/vue/LazyList.vue?vue&type=script&lang=js
```

As the error suggests, the `loading.css` file is missing from the `lib` directory. Judging from older versions of this, the code used to be in the `Loading` modules but was moved to an independent file which was never added to git.

### Suggested fix
Create a new file called `lib/loading.css` with the following:
```
.dots {
    width: 3.5em;
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    justify-content: space-between;
}

.dots div {
    width: 0.8em;
    height: 0.8em;
    border-radius: 50%;
    animation: fade 0.8s ease-in-out alternate infinite;
}

.dots div:nth-of-type(1) {
    animation-delay: -0.4s;
}

.dots div:nth-of-type(2) {
    animation-delay: -0.2s;
}

@keyframes fade {
    from {
        opacity: 1;
    }
    to {
        opacity: 0;
    }
}
```

**Comment by omer73364** [comment]
@p0rridg3 
The file is found but its name is "index.css"
I'm sorry for that error 😅

I fixed this issue and I have published new update to npm..
install last version of the package, please..

Thanks for notifying me of this issue 🌹

**Comment by p0rridg3** [comment]
Yup no worries
