### ISSUE TITLE
Uncaught TypeError: this.itemsToDisplay is not iterable

### ISSUE THREAD

**Issue by CasianBlanaru** [omer73364/lazy-load-list#4]
this.itemsToDisplay = [...this.itemsToDisplay, ...this.items[this.page]]

**Comment by omer73364** [comment]
Hi Casian, can please share your code of using the component..
perhaps you passed wrong data

**Comment by CasianBlanaru** [comment]
![Bildschirmfoto 2022-10-03 um 19 25 19](https://user-images.githubusercontent.com/23030087/193640381-42e4492c-b65b-40ec-8713-3e98443415
![Bildschirmfoto 2022-10-03 um 19 22 15](https://user-images.githubusercontent.com/23030087/193640389-d5501591-2806-47c2-bc1b-3e9d1b750abd.png)
a7.png)

**Comment by CasianBlanaru** [comment]
![Bildschirmfoto 2022-10-03 um 19 25 19](https://user-images.githubusercontent.com/23030087/193640453-9bf8dc07-8d68-40f8-bb6e-10b1a93fae7e.png)

**Comment by CasianBlanaru** [comment]
![Bildschirmfoto 2022-10-03 um 19 22 15](https://user-images.githubusercontent.com/23030087/193640498-f6f7c24e-01e6-465d-ba1a-aec3b2d62613.png)

**Comment by CasianBlanaru** [comment]
Hello omer73364 I hope this is enough ?

**Comment by CasianBlanaru** [comment]
In the frontend 10 items are displayed but the error occurs: 
![Bildschirmfoto 2022-10-03 um 19 30 51](https://user-images.githubusercontent.com/23030087/193641442-f1a78b00-323d-4d98-9fcb-928c7ab7795b.png)

**Comment by omer73364** [comment]
that's strange.. everything is OK, itemsToDisplay is an array but it cannot destruct it 🤔
whats your environment (vue version, bundler.. etc)?

and if you can debug it deeper will be OK to know the exact reason of this error

**Comment by CasianBlanaru** [comment]
Sorry for the late reply. I was able to fix the problem I built it with Vue and webpack 5 and had a wrong setting in the store ;-) Thanks for the support :-)

**Comment by Surt** [comment]
Hi,

same problem for me. It displays the first "page" but then it fails with the same error.
I'm doing nothing fanzy, just printing the "item.id" on a p tag. (from an array of objects)

I'm using nuxt 2 but I just import the Vue component and use it as normal. I doubt the environment has a play here.

EDIT: yep, it is environment. It seems that the problem resides in nuxt trying to use the component in SSR (where data is still not available). The watch is the one responsible for showing the first page.
